data = `
{
	"UseUnsafeWords": true,

	"Username": "Drew",

	"SafeReminders": [
		"Don't forget to",
		"Please don't forget to",
		"Make sure to",
		"You should",
		"You should probably",
		"You may want to",
		"You have to",
		"You HAVE to",
		"You know, I'd like it if you would",
		"Your computer would appreciate it if you would",
		"Make it a priority to",
		"You gotta",
		"You know you gotta",
		"For Pete the Cat's sake, please",
		"Jeremy told me he wants you to",
		"Joe just said that he was looking forward to seeing you"
	],

	"UnsafeReminders": [

	],

	"EndingPunctuation": [
		"!",
		".",
		"...",
		"!!!"
	],

	"SafeNouns": [
		"your cat",
		"your bubble hockey game",
		"Undertale",
		"your sad, lonely Undertale icon in your taskbar",
		"Deltarune",
		"Earthbound",
		"Joe",
		"Blacka",
		"Kate",
		"Bohince",
		"Girl-Don",
		"Jeremy",
		"the Penguins National Hockey League team",
		"Gor-Don",
		"your imaginary friend Wallace (yes, I know about him)",
		"your Ganon amiibo",
		"your Shulk amiibo",
		"your Mr. Game &amp; Watch amiibo",
		"your Zelda amiibo",
		"your Link amiibo",
		"your Marth amiibo",
		"your Roy amiibo",
		"your Ike amiibo",
		"your Sonic amiibo",
		"your Donkey Kong amiibo",
		"your Pit amiibo",
		"your Duck Hunt Dog amiibo",
		"your computer",
		"your Princess Rosalina amiibo",
		"your Charizard amiibo",
		"your ROB amiibo",
		"your Zero Suit Samus amiibo",
		"your Shovel Knight amiibo",
		"your Little Mac amiibo",
		"your Captain Falcon amiibo",
		"your Toon Link amiibo",
		"your Diddy Kong amiibo",
		"your Captain Olimar amiibo",
		"your Mega Man amiibo",
		"your Dark Pit amiibo",
		"your Mewtwo amiibo",
		"your Lucario amiibo",
		"your Pikachu amiibo",
		"your Jigglypuff amiibo",
		"your nonexistent Fox amiibo",
		"your nonexistent Falco amiibo",
		"your nonexistent Villager amiibo",
		"Brady",
		"Brundy",
		"Bonino Bonino Bonino",
		"a Budweiser brand Lime-a-rita",
		"a Budweiser brand Mango-a-rita",
		"a Budweiser brand Strawber-rita",
		"a Budweiser brand Bud Lite",
		"Super Meat Boy",
		"Gor-Don and Blacka",
		"Gor-Don and Joe",
		"Joe and Blacka",
		"Bohince and Gor-Don",
		"yourself",
		"everybody",
		"nothing in particular",
		"no one in particular",
		"Baba from cult classic 'Baba Is You'",
		"Gritty",
		"Gritty (the Philadelphian food processor)",
		"Ellen",
		"Joe's computer",
		"a chocolate bar with nuts",
		"a chocolate bar without nuts",
		"a chocolate bar with or without nuts",
		"your NUT button",
		"Nym's string",
		"the entire cast of Letterkenny",
		"a select few members of the cast of Letterkenny",
		"the last 'Game of Thrones' episode",
		"the second-to-last 'Game of Thrones' episode",
		"Gor-Don's Raspberry Pi",
		"Gor-Don's copy of Bayonetta 2 in your Wii U",
		"Werd, the opposite version of yourself"
		"fear itself",
		"pictures of boobs",
		"doing the right thing",
		"a balanced breakfast",
		"former president Barack Obama",
		"smegma",
		"the pope",
		"same-sex ice dancing",
		"Nickelback",
		"a falcon with a cap on its head",
		"a really cool hat",
		"a micropenis",
		"an Oedipus complex",
		"a sausage festival",
		"white people",
		"black people",
		"blue people",
		"colorless people",
		"a sassy black woman",
		"a docile white man",
		"a tiny horse",
		"a tiny house",
		"preteens",
		"balls",
		"a Tempur-Pedic Swedish Sleep System mattress",
		"Keanu Reeves",
		"the inevitable heat death of the universe",
		"a girl that you barely even know",
		"fiery poops",
		"daddy issues",
		"Jeremy when he calls you Daddy",
		"Joe when he watches The Expanse",
		"Gor-Don when he plays his Switch",
		"homeless people",
		"God",
		"Jesus",
		"a salty surprise",
		"Perenium Falcon, the rejected Star Wars spaceship",
		"Republicans",
		"Democrats",
		"Republicans and Democrats",
		"Moderates",
		"Libertarians",
		"explosions",
		"your soul",
		"your sex life",
		"Pabst Blue Ribbon",
		"bees(?)",
		"a bag of magic beans",
		"a snapping turtle biting the tip of your penis",
		"kids with ass cancer",
		"dick fingers",
		"a package of Lunchables",
		"hot cheese",
		"moldy cheese",
		"soup that is too hot",
		"soup that is too cold",
		"soup that is just the right temperature",
		"a baby with candy",
		"Nicolas Cage",
		"Santa Claus",
		"your dad dressed as Santa Claus",
		"your Daddy dressed as Santa Claus",
		"Borat when he is pondering about dairy products",
		"a sad, fat dragon with no friends",
		"Jeff Goldblum",
		"me (this web page)",
		"girls that always be textin'",
		"a for-real lizard that spits blood from its eyes",
		"sharks with legs",
		"oil (but pronounced like Bohince does in German)",
		"P.F. Chang himself",
		"a bass drop so huge it tears the starry vault asunder to reveal the face of God",
		"like a million alligators",
		"like a million crocodiles",
		"a burrito that's just sour cream",
		"a dolphin that learns to talk and becomes the Head of Harvard Law School",
		"a weird guy who does weird stuff and weirds you out",
		"big, smart money boys tap-tapping on their keyboards at an expensive downtown cafe",
		"a falcon with a box on its head",
		"a man-shaped box",
		"a box-shaped man",
		"Hodor",
		"the inaudible screams of carrots",
		"people with cake in their mouths talking about how good cake is",
		"Toby Fox",
		"Sans from Undertale"
	],

	"UnsafeNouns": [
		"Kristen",
		"Wintry Phoenix",
		"Wintry Cheeze Bits",
		"Speedy Pizza Puncher",
		"Kristen when she makes pizza",
		"Kristen when she makes confections",
		"Kristen when she makes breakfast",
		"Kristen when she plays her Switch"
		"a big black dick",
		"a dick so big and so black that not even light can escape its pull"
		"a completely average sized white dick",
		"a lamprey swimming up the toilet and latching onto your taint",
		"dem titties",
		"deez nuts",
		"ejaculating live bees and the bees are angry",
		"a pizza guy who fucked up",
		"a finger up the butt",
		"Albert Einstein but if he had huge muscles and a rhinoceros cock",
		"a dwarf who won't leave you alone until you compare penis sizes"
	],

	"SafeVerbs": [
		"work on",
		"enjoy",
		"consume",
		"punch",
		"defenestrate",
		"cry about",
		"think about",
		"play with",
		"yell at",
		"take a deep breath and then interact with",
		"buy a beer for",
		"buy ten beers for",
		"think platonic thoughts about",
		"talk passionately with",
		"have a farting contest with",
		"have a video game contest with",
		"drink a beer with",
		"drink ten beers with",
		"do a nice thing for",
		"do a mean thing toward",
		"enjoy a tender hug with",
		"enjoy a delicious Primati Brothers sandwich with",
		"look over the shoulder of",
		"contemplate relations with",
		"listen closely to",
		"talk dispassionately with",
		"text",
		"call",
		"catcall",
		"duckcall",
		"think of new ways to include",
		"study",
		"forget about",
		"whisper to",
		"scream at",
		"violently sneeze at",
		"dab at",
		"furiously dab at",
		"subtly dab at",
		"direct the press of your NUT button at",
		"kick",
		"complain about",
		"not complain to",
		"purchase",
		"purchase the services of",
		"give a loving pat on the head to",
		"have a roundtable discussion with",
		"go to sleep with",
		"leave an awkward voicemail for",
		"take off your shirt in front of",
		"drink a beer and think about",
		"take candy from",
		"burp at",
		"get married, have kids, buy some stuff, retire to Florida, and die with",
		"not wear pants with",
		"have a dream about",
		"have a wet dream about",
		"play Pokemon cards with",
		"play Yu-Gi-Oh cards with",
		"play a drinking game with",
		"play an eating game with",
		"have a hotdog eating contest with",
		"throw a virgin into a volcano with",
		"overpower",
		"give a boo-boo to",
		"chug a lava lamp with",
		"actually get shot, for real, by",
		"watch a cat video so cute that your eyes roll back and your spine slides out of your anus with",
		"re-enact Mufasa's death scene with",
		"have disco fever with",
		"create a spontaneous conga line with",
		"spend lots of money on",
		"not contribute to society in any meaningful way with",
		"cry over poetry with",
		"laugh over poetry with",
		"recite '10 Incredible Facts About the Anus' to",
		"eat a McRib with",
		"smoke crack (for instance) with",
		"go to a high school reunion on ketamine with",
		"get schwifty with",
		"catch a live salmon in your mouth and then feed it to",
		"defeat a gorilla in combat with",
		"do a somersault and barf onto",
		"eat too many Cinnabons and then vomiting and then eating the vomit with",
		"fall into a pit of waffles with",
		"fall into a pit of pancakes with",
		"get this party started with",
		"hate",
		"grade papers with",
		"practice political correctness with",
		"self-identity as",
		"take the form of",
		"create a bond similar to the one between a girl and her horse with",
		"give $20 to",
		"ask for $20 from",
		"get to the bottom of who really let the dogs out with",
		"ride a bus that will explode if it goes under 50 miles per hour with",
		"stab a Capri Sun way more than needed with",
		"discover that the real adventure was the friends we made along the way with",
		"give true love's kiss to",
		"go vegetarian with",
		"go vegan with",
		"laugh and eat a gratuitous amount of meat with",
		"swish wine around and sniff it like a big fancy man with",
		"match with your mom on Tinder and then message her like you do with",
		"wage World Wars 3 through 5 on",
		"wake up from this nightmare with",
		"screw up 'Silent Night' in front of 300 parents with your duet partner,",
		"watch Space Jam on VHS with",
		"share an immediately regrettable $9 hot dog from the Boston Convention Center with",
		"judge people by the color of their skin and not the content of their character with",
		"read YouTube comments with",
		"roll a D20 to determine initiative with",
		"play 'League of Legends' with",
		"offer to play 'League of Legends' with, but then retract the offer from",
		"stuff your balls into a Sega Genesis and press the power button with",
		"collect all the chaos emeralds with",
		"take 2d6 emotional damage from",
		"eat ribs so good they transcend race and class with",
		"save the rainforest with",
		"save the Rainforest Cafe with"
	],

	"UnsafeVerbs": [
		"dick",
		"pull out of",
		"literally eat shit with",
		"make the penises kiss with (or in front of)",
		"bitch slap",
		"take a man's eyes and balls out and put his eyes where his balls go and then his balls in the eye holes with",
		"avoid an ass disaster with",
		"do a dance move that's just sex with",
		"teach a girl how to handjob the penis featuring",
		"set your balls on fire and cartwheel to Ohio just to meet",
		"breastfeed in public like a radiant earth goddess for",
		"'grade papers' with",
		"make out and stuff with",
		"do the ol' Penis in the Popcorn surprise with",
		"give a dolphin a handjob for science with",
		"ejaculate a pound of tinsel onto"
	]
}
`;
