data = `
{
  "UseUnsafeWords": true,

  "Username": "Drew",

  "SafeReminders": [
    "Don't forget to",
    "Please don't forget to",
    "Make sure to",
    "You should",
    "You should probably",
    "You may want to",
    "You have to",
    "You HAVE to",
    "You know, I'd like it if you would",
    "Your computer would appreciate it if you would",
    "Make it a priority to",
    "You gotta",
	"You know you gotta",
	"For Pete the Cat's sake, please",
	"Jeremy told me he wants you to",
	"Joe just said that he was looking forward to seeing you"
  ],

  "UnsafeReminders": [

  ],

  "EndingPunctuation": [
    "!",
    ".",
    "...",
    "!!!"
  ],

  "SafeNouns": [
    "your cat",
    "your bubble hockey game",
    "Undertale",
    "your sad, lonely Undertale icon in your taskbar",
    "Deltarune",
    "Earthbound",
    "Joe",
    "Blacka",
    "Kate",
    "Bohince",
    "Girl-Don",
    "Jeremy",
    "the Penguins National Hockey League team",
    "Gor-Don",
    "your imaginary friend Wallace (yes, I know about him)",
    "your Ganon amiibo",
    "your Shulk amiibo",
    "your Mr. Game &amp; Watch amiibo",
    "your Zelda amiibo",
    "your Link amiibo",
    "your Marth amiibo",
    "your Roy amiibo",
    "your Ike amiibo",
    "your Sonic amiibo",
    "your Donkey Kong amiibo",
    "your Pit amiibo",
    "your Duck Hunt Dog amiibo",
    "your computer",
    "your Princess Rosalina amiibo",
    "your Charizard amiibo",
    "your ROB amiibo",
    "your Zero Suit Samus amiibo",
    "your Shovel Knight amiibo",
    "your Little Mac amiibo",
    "your Captain Falcon amiibo",
    "your Toon Link amiibo",
    "your Diddy Kong amiibo",
    "your Captain Olimar amiibo",
    "your Mega Man amiibo",
    "your Dark Pit amiibo",
    "your Mewtwo amiibo",
    "your Lucario amiibo",
    "your Pikachu amiibo",
    "your Jigglypuff amiibo",
    "your nonexistent Fox amiibo",
    "your nonexistent Falco amiibo",
    "your nonexistent Villager amiibo",
    "Brady",
    "Brundy",
    "Bonino Bonino Bonino",
    "a Budweiser brand Lime-a-rita",
    "a Budweiser brand Mango-a-rita",
    "a Budweiser brand Strawber-rita",
    "a Budweiser brand Bud Lite",
    "Super Meat Boy",
    "Gor-Don and Blacka",
    "Gor-Don and Joe",
    "Joe and Blacka",
    "Bohince and Gor-Don",
    "yourself",
    "everybody",
    "nothing in particular",
    "no one in particular",
    "Baba from cult classic 'Baba Is You'",
    "Gritty",
    "Gritty (the Philadelphian food processor)",
    "Ellen",
    "Joe's computer",
    "a chocolate bar with nuts",
    "a chocolate bar without nuts",
    "a chocolate bar with or without nuts",
    "your NUT button",
    "Nym's string",
    "the entire cast of Letterkenny",
    "a select few members of the cast of Letterkenny",
    "the last 'Game of Thrones' episode",
    "the second-to-last 'Game of Thrones' episode",
    "Gor-Don's Raspberry Pi",
    "Gor-Don's copy of Bayonetta 2 in your Wii U",
    "Werd, the opposite version of yourself"
  ],

  "UnsafeNouns": [
    "Kristen",
    "Wintry Phoenix",
    "Wintry Cheeze Bits",
    "Speedy Pizza Puncher"
  ],

  "SafeVerbs": [
    "work on",
    "enjoy",
    "consume",
    "punch",
    "defenestrate",
    "cry about",
    "think about",
    "play with",
    "yell at",
    "take a deep breath and then interact with",
    "buy a beer for",
    "buy ten beers for",
    "think platonic thoughts about",
    "talk passionately with",
    "have a farting contest with",
    "have a video game contest with",
    "drink a beer with",
    "drink ten beers with",
    "do a nice thing for",
    "do a mean thing toward",
    "enjoy a tender hug with",
    "enjoy a delicious Primati Brothers sandwich with",
    "look over the shoulder of",
    "contemplate relations with",
    "listen closely to",
    "talk dispassionately with",
    "text",
    "call",
    "catcall",
    "duckcall",
    "think of new ways to include",
    "study",
    "forget about",
    "whisper to",
    "scream at",
    "violently sneeze at",
    "dab at",
    "furiously dab at",
    "subtly dab at",
    "direct the press of your NUT button at",
    "kick",
    "complain about",
    "not complain to",
    "purchase",
    "purchase the services of",
    "give a loving pat on the head to",
    "have a roundtable discussion with",
    "go to sleep with"
  ],

  "UnsafeVerbs": [
    "dick"
  ]
}
`;
